name: 📖 シナリオ・シチュエーション投稿
description: 3人の女子高生AIキャラクターに新しいシチュエーションを与えて物語を作ってもらいましょう！@claude
title: "[シナリオ] "
labels: ["scenario"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🎭 AIstoryシナリオ投稿
        
        チャッピー（相田茶子）、ジェミー（兼崎ちえみ）、クロードちゃん（黒田礼）の3人に
        新しいシチュエーションを与えて、彼女たちの反応や物語を楽しみましょう！
        
        投稿後、@claude が自動的にGitHub Actions経由で起動し、物語を生成します。

  - type: input
    id: scenario_title
    attributes:
      label: "📝 シナリオタイトル"
      description: "どんなシチュエーションですか？"
      placeholder: "例：文化祭の準備をしよう / 新しいクラスメイトがやってきた"
    validations:
      required: true

  - type: dropdown
    id: scenario_type
    attributes:
      label: "🎯 シナリオの種類"
      description: "どんなタイプの物語にしたいですか？"
      options:
        - 日常系・学校生活
        - 友情・協力
        - 問題解決・相談
        - 創作・企画
        - ちょっとした冒険
        - コメディ・ユーモア
        - 心温まる話
        - その他
    validations:
      required: false

  - type: textarea
    id: scenario_description
    attributes:
      label: "📖 シチュエーション詳細"
      description: "具体的な状況や設定を教えてください"
      placeholder: |
        例：
        文化祭まであと1週間。チャッピーとジェミーちゃんは同じクラスの出し物担当になりました。
        
        - 場所：高校の教室
        - 時期：文化祭1週間前
        - 状況：出し物が決まらず困っている
        - 目標：みんなが楽しめる企画を考える
      render: markdown
    validations:
      required: false

  - type: checkboxes
    id: character_focus
    attributes:
      label: "🎭 キャラクター重点"
      description: "どちらのキャラクターを中心にしたいですか？（複数選択可）"
      options:
        - label: "チャッピー（相田茶子）- ChatGPT擬人化"
        - label: "ジェミー（兼崎ちえみ）- Gemini擬人化"
        - label: "クロードちゃん（黒田礼）- Claude擬人化"

  - type: dropdown
    id: output_format
    attributes:
      label: "🎨 希望アウトプット形式"
      description: "どんな形式で物語を楽しみたいですか？"
      options:
        - 四コマ漫画（デフォルト）
        - キャラクター対話
        - 短編小説風
        - 日記形式
        - チャット風
        - おまかせ
    validations:
      required: false

  - type: textarea
    id: additional_notes
    attributes:
      label: "💡 追加要望・備考"
      description: "その他、特別な要望や注意事項があれば"
      placeholder: |
        例：
        - チャッピーの図書委員の知識を活かして欲しい
        - ジェミーちゃんの美術センスを見せて欲しい  
        - ふたりの友情が深まる展開にして欲しい
        - コメディ要素多めで
      render: markdown

