name: 📊 ユーザー評価・フィードバック
description: 生成された物語の10段階評価とフィードバックを送信
title: "[評価] "
labels: ["user-evaluation"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 📊 物語評価システム
        
        生成された物語に対する10段階評価とフィードバックをお願いします。
        この評価データはAIの学習に使用され、より面白い物語生成に活用されます。

  - type: input
    id: story_reference
    attributes:
      label: "📖 評価対象の物語"
      description: "評価する物語のIssue番号またはタイトル"
      placeholder: "例：#1 文化祭の準備 / 2024-01-08_cultural_festival"
    validations:
      required: true

  - type: dropdown
    id: user_rating
    attributes:
      label: "⭐ 総合評価（10段階）"
      description: "物語全体の面白さを10段階で評価してください"
      options:
        - "10 - 非常に面白い！完璧！"
        - "9 - とても面白い"
        - "8 - 面白い"
        - "7 - まあまあ面白い"
        - "6 - 普通より少し良い"
        - "5 - 普通"
        - "4 - 普通より少し悪い" 
        - "3 - あまり面白くない"
        - "2 - つまらない"
        - "1 - 全くつまらない"
    validations:
      required: true

  - type: checkboxes
    id: good_points
    attributes:
      label: "👍 良かった点（複数選択可）"
      description: "特に良かった要素を選択してください"
      options:
        - label: "チャッピーのキャラクターが良い"
        - label: "ジェミーちゃんのキャラクターが良い"
        - label: "キャラクター同士の掛け合いが面白い"
        - label: "会話のテンポが良い"
        - label: "オチが面白い・意外"
        - label: "物語の構成が良い"
        - label: "設定・シチュエーションが良い"
        - label: "読みやすい"

  - type: checkboxes
    id: improvement_points
    attributes:
      label: "📝 改善点（複数選択可）"
      description: "改善して欲しい要素を選択してください"
      options:
        - label: "チャッピーのキャラクターがブレている"
        - label: "ジェミーちゃんのキャラクターがブレている"
        - label: "会話が不自然"
        - label: "話が長すぎる"
        - label: "オチが弱い・つまらない"
        - label: "物語の構成が悪い"
        - label: "設定が活かされていない"
        - label: "読みにくい"

  - type: textarea
    id: detailed_feedback
    attributes:
      label: "💬 詳細フィードバック"
      description: "具体的な感想や改善提案があればお書きください"
      placeholder: |
        例：
        - チャッピーのギャル語がもっと強くても良い
        - ジェミーちゃんの「規約により〜」がもっと欲しい
        - もう少し短くまとめて欲しい
        - こういう展開が見たい
      render: markdown

  - type: dropdown
    id: promotion_decision
    attributes:
      label: "🚀 昇格判定"
      description: "この物語をネーム化（4コマ漫画）に昇格させますか？"
      options:
        - "昇格させる（ネーム化して欲しい）"
        - "昇格させない（このままで十分）"
        - "改善後に再検討"
    validations:
      required: true

  - type: checkboxes
    id: system_feedback
    attributes:
      label: "🔧 システムについて"
      description: "評価システム自体についてのフィードバック"
      options:
        - label: "評価項目は適切"
        - label: "もっと詳細な評価項目が欲しい"
        - label: "評価方法を改善して欲しい"
        - label: "結果の反映が早い"
        - label: "結果の反映が遅い"