name: Claude Code Action

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  claude:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.body, '@claude') || contains(github.event.comment.body, '@claude')
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Claude Code Action
        uses: anthropics/claude-code-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}