name: Claude Code Action

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  claude:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.body, '@claude') || contains(github.event.comment.body, '@claude')
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Debug OAuth Token Setup
        run: |
          echo "🔍 Checking CLAUDE_CODE_OAUTH_TOKEN environment variable..."
          if [ -z "$CLAUDE_CODE_OAUTH_TOKEN" ]; then
            echo "❌ CLAUDE_CODE_OAUTH_TOKEN is not set or empty"
            echo "Please ensure CLAUDE_CODE_OAUTH_TOKEN is configured in GitHub Secrets"
            echo "OAuth setup guide: https://note.com/lab_bit__sutoh/n/nc39cc4ea33f0"
            exit 1
          else
            echo "✅ CLAUDE_CODE_OAUTH_TOKEN is set (length: ${#CLAUDE_CODE_OAUTH_TOKEN} characters)"
          fi
        env:
          CLAUDE_CODE_OAUTH_TOKEN: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
        
      - name: Claude Code Action
        uses: anthropics/claude-code-action@main
        env:
          CLAUDE_CODE_OAUTH_TOKEN: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}